### ISSUE TITLE
Unknown property "breadcrumbs_label"

### ISSUE THREAD

**Issue by develaper** [yceruto/breadcrumbs-bundle#1]
Hi!
I am using this bundle with Symfony3.
As suggested in the Symfony docs I added the routing at the beginning of each controller:
```
namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    /**
     * @Route("/{page}", name="homepage", requirements={"page": "\d+"}, breadcrumbs_label="Home")
     */
    public function indexAction($page = 1)
    {
        //...
    }
}
```

But I get this error when I try to browse the Home page:

> Unknown property "breadcrumbs_label" on annotation "Sensio\Bundle\FrameworkExtraBundle\Configuration\Route"
Any suggestions about how should I proceed?
Thanks.

**Comment by yceruto** [comment]
Hi @develaper, you need to put it inside `defaults` option i.e.:
```
@Route("/{page}", ..., defaults={"breadcrumbs_label": "Home"})
```

**Comment by develaper** [comment]
Thanks! Works like a charm!!
